AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  back-end

  Sample SAM Template for back-end

Globals:
  Function:
    Timeout: 3

Parameters:
  BucketPrefix:
    Type: String
    Description: Prefix for the S3 Bucket that contains visitor logs
    Default: cloud-resume-visitor-logs
  DeliveryStreamName:
    Type: String
    Description: Name of the Data Firehose that transforms and sends the logs to S3
    Default: cloud-resume-visitor-log-stream
  CompressionFormat:
    Type: String
    Description: Compression format for S3 files
    AllowedValues:
      - UNCOMPRESSED
      - GZIP
      - ZIP
      - Snappy
    Default: UNCOMPRESSED
  BufferingIntervalInSeconds:
    Description: >
      Buffer incoming data for the specified period of time, in seconds, before delivering it to the destination.
      See https://docs.aws.amazon.com/firehose/latest/APIReference/API_BufferingHints.html for details.
    Type: Number
    MinValue: 60
    MaxValue: 900
    Default: 300
  BufferingSizeInMBs:
    Description: >
      Buffer incoming data to the specified size, in MBs, before delivering it to the destination. Note, if you specify a DataTransformationLambdaFunctionArn, you should
      not set this higher than 6. See https://docs.aws.amazon.com/firehose/latest/dev/data-transformation.html for details.
    Type: Number
    MinValue: 1
    MaxValue: 128
    Default: 5
  DynamoTableName:
    Type: String
    Description: Name of the DynamoDB table that holds the formatted cloud resume visitor logs
    Default: cloud-resume-visitor-logs

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketNamePrefix: !Ref BucketPrefix
      BucketNamespace: account-regional

  DeliveryStreamProcessingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: transform_log/
      Handler: app.lambda_handler
      Runtime: python3.14
      Architectures:
        - x86_64

  DeliveryStreamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - firehose.amazonaws.com
            Action:
              - sts:AssumeRole
            Condition:
              StringEquals:
                sts:ExternalId: !Sub ${AWS::AccountId}
      Policies:
        - PolicyName: S3ReadWrite
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - s3:AbortMultipartUpload
                  - s3:GetBucketLocation
                  - s3:GetObject
                  - s3:ListBucket
                  - s3:ListBucketMultipartUploads
                  - s3:PutObject
                Resource:
                  - !GetAtt Bucket.Arn
                  - !Sub ${Bucket.Arn}/*
              - Effect: Allow
                Action: lambda:InvokeFunction
                Resource: !GetAtt DeliveryStreamProcessingFunction.Arn

  DeliveryStream:
    Type: AWS::KinesisFirehose::DeliveryStream
    Properties:
      DeliveryStreamName: !Ref DeliveryStreamName
      DeliveryStreamType: DirectPut
      ExtendedS3DestinationConfiguration:
        BucketARN: !GetAtt Bucket.Arn
        RoleARN: !GetAtt DeliveryStreamRole.Arn
        BufferingHints:
          IntervalInSeconds: !Ref BufferingIntervalInSeconds
          SizeInMBs: !Ref BufferingSizeInMBs
        CompressionFormat: !Ref CompressionFormat
        Prefix: "year=!{timestamp:YYYY}/month=!{timestamp:MM}/day=!{timestamp:dd}/"
        ErrorOutputPrefix: "errors/!{firehose:error-output-type}/year=!{timestamp:YYYY}/month=!{timestamp:MM}/day=!{timestamp:dd}/"
        ProcessingConfiguration:
          Enabled: True
          Processors:
            - Type: Lambda
              Parameters:
                - ParameterName: LambdaArn
                  ParameterValue: !GetAtt DeliveryStreamProcessingFunction.Arn

  EventToFirehoseFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: FirehoseWrite
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - firehose:PutRecord
                  - firehose:PutRecordBatch
                Resource: !GetAtt DeliveryStream.Arn

  EventToFirehoseFunction:
    Type: AWS::Serverless::Function
    Properties:
      Role: !GetAtt EventToFirehoseFunctionRole.Arn
      CodeUri: event_to_firehose/
      Handler: app.lambda_handler
      Runtime: python3.14
      Architectures:
        - x86_64
      Events:
        EventToFirehose:
          Type: Api
          Properties:
            Path: /log
            Method: post

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: epoch
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: epoch
          AttributeType: N
      TableName: !Ref DynamoTableName
      BillingMode: PAY_PER_REQUEST

  S3ToDynamoFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3Read
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource:
                  - !GetAtt Bucket.Arn
                  - !Sub ${Bucket.Arn}/*

  S3ToDynamoFunction:
    Type: AWS::Serverless::Function
    Properties:
      Role: !GetAtt S3ToDynamoFunctionRole.Arn
      CodeUri: s3_to_dynamo/
      Handler: app.lambda_handler
      Runtime: python3.14
      Architectures:
        - x86_64

Outputs:
  BucketName:
    Description: Data bucket name
    Value: !Ref Bucket
  BucketArn:
    Description: Data bucket ARN
    Value: !GetAtt Bucket.Arn

  DeliveryStreamName:
    Description: Kinesis Data Firehose delivery stream name
    Value: !Ref DeliveryStream
  DeliveryStreamArn:
    Description: Kinesis Data Firehose delivery stream ARN
    Value: !GetAtt DeliveryStream.Arn

  EventToFirehoseApi:
    Description: "API Gateway endpoint URL for Prod stage for Event To Firehose function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/log/"
  EventToFirehoseFunction:
    Description: "Event To Firehose Lambda Function ARN"
    Value: !GetAtt EventToFirehoseFunction.Arn
  EventToFirehoseFunctionIamRole:
    Description: "Implicit IAM Role created for Event To Firehose function"
    Value: !GetAtt EventToFirehoseFunctionRole.Arn

  DynamoDBTableName:
    Description: DynamoDB table name
    Value: !Ref DynamoTableName
  DynamoDBTableArn:
    Description: DynamoDB table ARN
    Value: !GetAtt DynamoDBTable.Arn
